ARG BASE_IMAGE

FROM $BASE_IMAGE

# Install required dependencies
RUN yum install gcc -y  \
                cpp \
                glibc-devel \ 
                glibc-headers \
                isl \
                libgomp \
                libmpc \
                libxcrypt-devel \ 
                make \
                elfutils-libelf-devel \
                elfutils-libelf \
                elfutils-libs \
                zlib \
                libzstd-devel \
                zlib-devel \
                elfutils-debuginfod-client \
                unzip \
                kernel-devel \
                kernel-headers \
                && \
     yum group install "Development Tools" -y && \
     yum clean all

