name: Stress Test Workflow

env:
  GPGPackageKey: ${{ secrets.GPGPACKAGEKEY }}
  GPGPackagePassphrase: ${{ secrets.GPGPACKAGEPASSPHRASE }}
  KEYNAME: ${{ secrets.KEYNAME }}

on:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description:
        options:
        - stress-Test

jobs:
  build:
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'stress-Test'
    container:
      image: thinkpranav/almalinux8-build-essential@sha256:0f575dcf9908b5d19395dc1d5dd2843f3e0ca75b693ebccfa7b3d0c3b1b04c28
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Building packages
        run: |
          export CONCURRENCY="$(nproc)"
          export MAKEFLAGS="-j $CONCURRENCY"
          export BEEGFS_VERSION="$(test -n "${CI_COMMIT_TAG}" && echo "${CI_COMMIT_TAG}" || git describe --tags --match '*.*' --abbrev=8)"
          export GPG_TTY=$(tty)
          echo "bash .ci/build/packages.sh rpm"

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/
          retention-days: 3
      - name: Cleanup to download packages
        run: echo "bash .github/workflows/cleanup.sh"


  stress-test-testing:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          fetch-depth: 0

      - name: Download packages artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages/

      - name: Running stress test
        run: |
          export CI_JOB_ID="$(test -n "${CI_COMMIT_TAG}" && echo "${CI_COMMIT_TAG}" || git describe --tags --match '*.*' --abbrev=8)_${GITHUB_RUN_ID}_$(date "+%d%m%y_%H_%M")"
          echo "Stress Test Testing $CI_JOB_ID"
          echo "bash .ci/stress-test-setup/scripts/stress-setup.sh"



