name: 'Hello World'
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Select the package type to build (RPM or DEB)'
        options:
          - DEB
      imageName:
        description: 'Name of the Docker image which will be created from base image'
        required: true
      baseImage:
        description: 'Base Docker image to use'
        required: true

jobs:
  build:
    name: 'Hello World'
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Step
        run: echo "Hello" >> greetings.txt
      - name: Record Time Step
        runs:
          using: 'docker'
          image: 'Dockerfile'
         
