name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Name of the Docker image (including the repository name if pushing to DockerHub or another registry)'
        required: true
        default: 'yourusername/myapp:latest' # Example default image name, replace with your own default
      baseImage:
        description: 'Base Docker image to use'
        required: true
        default: 'node:14' # Example default base image, replace with your desired base image

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
    
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
             
      - 
        name: Build and push
        run: |
           docker build -t ${{ github.event.inputs.imageName }} \
                     --build-arg BASE_IMAGE=${{ github.event.inputs.baseImage }} \
                     .
            docker push ${{ github.event.inputs.imageName }}
