name: Stress Test Workflow

env:
  GPGPackageKey: ${{ secrets.GPGPACKAGEKEY }}
  GPGPackagePassphrase: ${{ secrets.GPGPACKAGEPASSPHRASE }}
  KEYNAME: ${{ vars.GPGKEYNAME }}

on:
  workflow_dispatch:
    inputs:
      stress-test:
        description: 'Stress test configuration'
        required: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: thinkpranav/almalinux8-build-essential@sha256:0f575dcf9908b5d19395dc1d5dd2843f3e0ca75b693ebccfa7b3d0c3b1b04c28
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Building packages
        run: |
          export CONCURRENCY="$(nproc)"
          export MAKEFLAGS="-j $CONCURRENCY"
          export BEEGFS_VERSION="$(git describe --tags --match '*.*' --abbrev=8)"
          export GPG_TTY=$(tty)
          echo BEEGFS_VERSION is ${BEEGFS_VERSION}
          echo "bash .ci/build/packages.sh rpm"

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/
          retention-days: 1

