name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Name of the Docker image (including the repository name if pushing to DockerHub or another registry)'
        required: true
        
      baseImage:
        description: 'Base Docker image to use'
        required: true
        

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: aditya5900
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build and push
        run: |
           docker build -t ${{ github.event.inputs.imageName }} \
                     --build-arg BASE_IMAGE=${{ github.event.inputs.baseImage }} \
                     .
            docker push ${{ github.event.inputs.imageName }}
